spring.application.name=Entreprise
### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/entreprise?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true
spring.datasource.username=root
spring.datasource.password=
# ## JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8088

# Enregistrement auprès d'Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true


# Configuration MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect








# Disable config server check
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
# MySQL Configuration

spring.jpa.properties.hibernate.format_sql=true



pring.cloud.config.fail-fast=true
