services:
  eureka:
    build: ./Eureka
    image: eureka:1.0
    container_name: eurekacontainer
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  apigateway:
    build: ./API-GATEWAY
    image: apigateway:1.0
    container_name: apigatewaycontainer
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    depends_on:
      - eureka
    networks:
      - mynetwork

  document:
    build: ./Document
    image: document:1.0
    container_name: documentcontainer
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/DocumentMS?createDatabaseIfNotExist=true&useSSL=false&max_allowed_packet=15728640
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - eureka
      - db_mysql
      - apigateway
    networks:
      - mynetwork

  db_mysql:
    image: mysql:5.7
    container_name: db_mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
    networks:
      - mynetwork
    volumes:
      - C:/xampp/mysql/data/documentms:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge
