spring.main.web-application-type=reactive
spring.application.name=GateWay
server.port=8085
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.gateway.routes[0].id=offrestage
spring.cloud.gateway.routes[0].uri=lb://OffreStage
spring.cloud.gateway.routes[0].predicates[0]=Path=/offreStage/**
# Route vers le microservice User
spring.cloud.gateway.routes[1].id=user
spring.cloud.gateway.routes[1].uri=lb://user
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**


spring.cloud.gateway.routes[2].id=entreprise-service
spring.cloud.gateway.routes[2].uri=lb://ENTREPRISE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/entreprises/**

spring.cloud.gateway.routes[3].id=document-service
spring.cloud.gateway.routes[3].uri=lb://DOCUMENT
spring.cloud.gateway.routes[3].predicates[0]=Path=/documents/**

# Route vers le service VALIDATION-SERVICE
spring.cloud.gateway.routes[4].id=validation-service
spring.cloud.gateway.routes[4].uri=lb://VALIDATION-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/validations/**
logging.level.com.netflix.discovery=DEBUG
logging.level.com.netflix.eureka=DEBUG
