# Nom de l'application (Eureka Server)
spring.application.name=Eureka_Server

# Port d'Eureka Server
server.port=8761

# Configurer Eureka pour ne pas essayer de se connecter à un autre registre (car c'est un serveur)
eureka.client.fetch-registry=false

# Indiquer à Eureka de ne pas s'enregistrer lui-même sur un autre registre (ce n'est pas nécessaire car c'est un serveur)
eureka.client.register-with-eureka=false

# URL du serveur Eureka pour la découverte des services
eureka.server.enableSelfPreservation=false

# Configuration des zones (si tu veux avoir des zones multiples, tu peux les configurer ici)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Activer les logs pour Eureka
logging.level.com.netflix.discovery=DEBUG
logging.level.com.netflix.eureka=DEBUG
